# Generated by Django 5.0.2 on 2024-02-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('numero_de_telefono', models.IntegerField()),
                ('producto', models.CharField(max_length=100)),
                ('metodo_de_pago', models.CharField(max_length=50)),
            ],
        ),
    ]
